### ISSUE TITLE
Mg/Mg2+ charged simulation 

### ISSUE THREAD

**Issue by Rickk-Rickk** [alex-aziz/Modelling-Mg-surfaces-implicit-solvent-models#1]
Hi Dr. @alex-aziz,
I have a query regarding the 2022 paper https://doi.org/10.1063/5.0087683. It is a very detailed piece of work emphasizing the effect of implicit and explicit water environment on the Mg2+ dissolution.
It is mentioned in the methods section that the Mg2+ ions are fixed symmetrically 7 Å from the Mg surface. Does that mean the Mg2+ and all the 6 water molecules are fixed in there position?
Also, when Mg(6H2O)2+ is included, are the simulations are uncharged? If uncharged, by doing so I believe it allows charge transfer among the Mg surface and Mg2+ ion.

Thank you.

**Comment by alex-aziz** [comment]
Thanks for the message. 

Yes, they are fixed in this position. It is close enough to allow charge transfer between the surface and the Mg2+ but far enough so there is minimal interaction between the surface and the Mg2+. In the simulations the number of electrons (and hence the potential) is changed and the potential where the free energy curves meet indicates the potential where the two systems are at equilibrium, and where each system becomes more stable. Please also refer to https://doi.org/10.1039/C9CP06684E as this may also help you. 

Best wishes,
Alex
